"""
Django settings for socialwebsite project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '$59k=0ptmlzy^o8s4w2kb^k!=@**7*(zu%)e@viwl2@*l39f4w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
THUMBNAIL_DEBUG = True

ALLOWED_HOSTS = ['mysite.com', 'localhost', '127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'django_extensions', 
    'account.apps.AccountConfig',
    'images.apps.ImagesConfig', 
    'actions.apps.ActionsConfig', 
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'social_django',
    'easy_thumbnails', 
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'socialwebsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 'socialwebsite.context_processors.global_processor',
            ],
        },
    },
]

# CSRF_COOKIE_SECURE = True
# SESSION_COOKIE_SECURE = True - If you have set the CSRF_COOKIE_SECURE to be True in your settings file, then the cookie will be marked as "secure" and therefore will need an HTTPS connection.

WSGI_APPLICATION = 'socialwebsite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = '/media/' 
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/') 

LOGIN_REDIRECT_URL = 'dashboard' 
LOGIN_URL = 'login' 
LOGOUT_URL = 'logout' 

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' 
# EMAIL_HOST = 'smtp.gmail.com' 
# EMAIL_HOST_USER = 'yannidimitrova@gmail.com' 
# EMAIL_HOST_PASSWORD = 'nani4kas'
# EMAIL_PORT = 1025 
# EMAIL_USE_TLS = True 

AUTHENTICATION_BACKENDS = [    
    'django.contrib.auth.backends.ModelBackend',    
    'account.authentication.EmailAuthBackend', 
    'social_core.backends.facebook.FacebookOAuth2', 
] 

SOCIAL_AUTH_FACEBOOK_KEY = '728721734444757' # Facebook App ID 
SOCIAL_AUTH_FACEBOOK_SECRET = '9d93d2e5d5d0eacfaab32888abc8adc7' # Facebook App Secret 

ABSOLUTE_URL_OVERRIDES = {    
    'auth.user': lambda u: reverse_lazy('user_detail', args=[u.username]) 
    } 


REDIS_HOST = 'localhost' 
REDIS_PORT = 6379 
REDIS_DB = 0 